#服务器端口配置
server:
 port: 8081
 tomcat:
  #tomcat编码设置为UTF-8
  uri-encoding: UTF-8
  threads:
   #最大线程数设置为800，默认为200
   max: 800
   #Tomcat启动初始化的线程数，默认值为25，这里设置为30
   min-spare: 30



spring:
  # 数据源配置
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/vueadmin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
   username: root
   password: admin
   type: com.alibaba.druid.pool.DruidDataSource

    #druid 数据源专有配置
   initialSize: 5
   minIdle: 5
   maxActive: 20
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 1 FROM DUAL
   testWhileIdle: true
   testOnBorrow: false
   testOnReturn: false
   poolPreparedStatements: true
   #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
   #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
   #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
   filters: stat,wall,log4j
   maxPoolPreparedStatementPerConnectionSize: 20
   useGlobalDataSourceStat: true
   connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  #spring security配置
  security:
   user:
    name: user
    password: admin
  #热部署开关
  devtools:
   restart:
    enabled: true

#mapper扫描位置
mybatis-plus:
 mapper-locations: classpath*:/mapper/**Mapper.xml

ruoyan:
 jwt:
  header: Authorization
  expire: 604800
  secret: d1212ij12129dj1aldj11209dd122hds

#日志配置
logging:
 level:
   com.ruoyan: debug
   org.springframework: warn
